### ISSUE TITLE
Getting Started: Hello World!

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#1]
**Description**
Create a hello world program and describe the basics on how to compile and run a single file.

**Tasks**

- [x] Create a hello world program.
- [ ] Describe how `printf()` works in the simplest way possible. Include link to C I/O #3 .
- [ ] Link to C strings. #17

**Comment by kchevali** [comment]
Also include how commenting works.

**Comment by kchevali** [comment]
Describe how 'printf()' in the most simple way possible. Should include a link to C I/O, which will go more in depth.
