### ISSUE TITLE
Fundamentals: Comparison Operators

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#12]
**Description**
Describe the basic comparison operators: `==`, `!=`, `>`, `<`, `>=`, `<=`.

**Tasks**

- [ ] Describe and list operators.
- [ ] Link to all operators. #9 
- [ ] Link to the assignment operator in statements and variables page. #5
