### ISSUE TITLE
Fundamentals: Bitwise Operators

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#13]
**Description**
Describe the basic bitwise operators: `&`, `|`, `^`, `~`, `<<`, `>>` and their derivatives such as `&=`.

**Tasks**
- [ ] Describe what a bit is.
- [ ] Describe the basic operators with truth tables.
- [ ] Compare to the logical operators. #11 
- [ ] Link to all operators. #9
