### ISSUE TITLE
Getting Started: I/O in C++

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#16]
**Description**
Describe the basics of i/o in c++.

**Tasks**

- [ ] Introduce i/o with `cin` and `cout` and `endl`.
- [ ] Describe the `<<` and the `>>` operators.
- [ ] Describe file i/o in C++.
- [ ] Link to all operators page. #9 
- [ ] Link to i/o with C and don't include comparison here. #3
