### ISSUE TITLE
Getting Started: C strings

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#17]
**Description**
Describe what c strings are.

**Tasks**
- [x] Go over data type of c string.
- [x] Short comparison to `std::string`.
- [x] Go over c methods for c strings.
- [x] Go over iterating through c strings - include null terminator.
- [x] Link to variables #5, `std::string` #25, all data types #6, chars in primitive data types #4, arrays #26,  escape sequences #24.
