### ISSUE TITLE
Fundamentals: File Input and Output in C

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#18]
**Description**
Describe how to read and write from a file using the `FILE` struct.

**Tasks**
- [ ] Introduce the `fscanf()` and `fprintf()` functions.
- [ ] Describe the `FILE` struct
- [ ] Link to i/o for c page. #3 
- [ ] Link to structs page. #19 
- [ ] Link to all data types page. #6
