### ISSUE TITLE
Structs

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#19]
**Description**
Describe what structs are.

**Tasks**
- [ ] How to create a struct and what they are for.
- [ ] Link to `FILE` struct. #18 
- [ ] Link to member operators page. #20 
- [ ] Comparison and link to class page.
