### ISSUE TITLE
Getting Started: Branching

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#2]
**Description**
Describe if, else if, and else statements.

**Tasks**
- [x] Add description of branching.
- [x] List types of branching statements.
- [x] Link to loops #7 and switch statement #8 for comparison.
- [x] Link to scope. #21
