### ISSUE TITLE
Fundamentals: Member Operator

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#20]
**Description**
Describe the basic bitwise operators: `.` and `->`.

**Tasks**
- [ ] Overview of the operators.
- [ ] Link to struct #19 and class pages.
- [ ] Link to all operators page. #9
