### ISSUE TITLE
Getting Started: Functions

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#22]
**Description**
Overview of functions.

**Tasks**
- [ ] Go over the purpose and syntax of functions.
- [ ] Mention the difference between functions and methods.
- [ ] Link to statements and variable page. #5
- [ ] Link to scope. #21
