### ISSUE TITLE
Casting

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#23]
**Description**
Overview of casting.

**Tasks**
- [ ] What is upcasting vs downcasting?
- [ ] Explicit vs implicit casting.
- [ ] Casting operator in C and link to general operator page. #9 
- [ ] Different types of casting in C++, such as `dynamic_cast`, `static_cast`, `const_cast`, and `reinterpret_cast`.
