### ISSUE TITLE
Fundamentals: Escape Sequences

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#24]
**Description**
Overview of the basic escape syntax in a string or character.

**Tasks**
- [ ] Description and purpose of escape sequences.
- [ ] Link to c-style strings. #17 
- [ ] Link to primitive types for the char type. #4
