### ISSUE TITLE
Fundamentals: C++ Strings

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#25]
**Description**
Describe what c++ strings are.

**Tasks**
- [ ] Go over data type of c++ string.
- [ ] Link to c style strings. #17 
- [ ] Go over methods for c++ strings.
- [ ] Mention limits to use with c functions and i/o. #3
- [ ] Link to all data types #6, chars in primitive data types #4 and objects.
