### ISSUE TITLE
Fundamentals: Arrays

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#26]
**Description**
Overview of arrays.

**Tasks**
- [ ] Purpose of arrays.
- [ ] Different syntax for array declaration/initialization.
- [ ] Link to arrays can be of any type. #6
- [ ] Link to arrays as pointers.
- [ ] Link to array(pointer) operators. #15 
- [ ] Link between arrays and loops. #7 
- [ ] Passing arrays into functions with link. #22
