### ISSUE TITLE
Getting Started: I/O in C

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#3]
**Description**
Basic points about input and output in C.

**Tasks**
- [x] Introduce `scanf()` and `printf()`.
- [x] Link to file input and output. #18 
- [x] Compare to i/o in c++ and link to it. #16 
- [x] Describe what formatted i/o is.
- [x] List the data type codes for formatted i/o. Link to the primitive data type file #4 and c style strings #17.
- [x] Very briefly describe `\n` and link to the escape sequences file. #24
