### ISSUE TITLE
Getting Started: Primitive data types

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#4]
**Description**
List all of the primitive data types and some information about each.

**Tasks**
- [ ] Describe what a primitive data type is.
- [ ] Link to some non-primitive data types: `FILE` #18 and `C string` #17 .
- [ ] List the data type name, size and any other information
- [ ] For `bool`: link to the branching #2 and loops #7 pages.
- [ ] Go over `signed` vs `unsigned` integer types.
- [ ] Link to general data type page. #6
