### ISSUE TITLE
Getting Started: Statements and Variables

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#5]
**Description**
Describe what statements and variables are.

**Tasks**
- [x] Describe what statements are. Mention/describe constants and link to functions page. #22 
- [x] Describe what variables are and link to the data type file. #6 
- [x] Include syntax rules.
- [x] Describe the assignment operator and link to the operator's page. #9
- [x] Link to scope. #21
