### ISSUE TITLE
Getting Started: All Data Types

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#6]
**Description**
Describe what are data types

**Tasks**
- [ ] Description of what a data type is.
- [ ] Link to primitive data types. #4
- [ ] Link to other non-primitive data types. #17 #18
