### ISSUE TITLE
Getting Started: Loops

### ISSUE THREAD

**Issue by kchevali** [kchevali/CppGuide#7]
**Description**
Describe loops and list what they are.

**Tasks**
- [ ] What are loops and why use them?
- [ ] List loops
- [ ] Basic pros and cons of each loop type.
- [ ] Link to primitive type page at bool section. #4 
- [ ] Link to branching page for comparison. #2 
- [ ] Link to scope. #21
